pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/dxvya-gh/Agile17.git'
            }
        }

        stage('Build') {
            steps {
                dir('project-1-student-registration') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('project-1-student-registration') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('project-1-student-registration') {
                    bat 'mvn package'
                }
            }
        }
    }
}