pipeline {
    agent any

    stages {
        stage('Parallel Checks') {
            parallel {
                stage('Frontend Check') {
                    steps {
                        dir('project-3-parallel') {
                            bat 'python frontend_check.py'
                        }
                    }
                }

                stage('Backend Check') {
                    steps {
                        dir('project-3-parallel') {
                            bat 'python backend_check.py'
                        }
                    }
                }
            }
        }

        stage('Summary') {
            steps {
                echo 'Frontend and Backend checks completed successfully.'
            }
        }
    }
}